"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { Download, Search, CheckCircle2, XCircle } from "lucide-react";

interface Referral {
  id: string;
  referrer_id: string;
  referred_id: string;
  status: "pending" | "successful" | "rewarded" | "rejected";
  reward_status: "pending" | "rewarded";
  created_at: string;
  referrer: {
    full_name: string | null;
    email: string;
  } | null;
  referred: {
    full_name: string | null;
    email: string;
  } | null;
}

export default function AdminReferrals() {
  const [referrals, setReferrals] = useState<Referral[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [actioningId, setActioningId] = useState<string | null>(null);

  const fetchReferrals = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from("referral_records")
      .select(`
        *,
        referrer:users!referrer_id(full_name, email),
        referred:users!referred_id(full_name, email)
      `)
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Error fetching referrals:", error.message);
    } else if (data) {
      // Map to ensure structured typing
      const mapped = data.map((item: any) => {
        const referrerUser = Array.isArray(item.referrer) ? item.referrer[0] : item.referrer;
        const referredUser = Array.isArray(item.referred) ? item.referred[0] : item.referred;
        return {
          ...item,
          referrer: referrerUser || null,
          referred: referredUser || null
        };
      });
      setReferrals(mapped);
    }
    setLoading(false);
  };

  useEffect(() => {
    fetchReferrals();
  }, []);

  const handleApprove = async (record: Referral) => {
    if (!window.confirm(`Are you sure you want to approve this referral? This will automatically generate a 20% OFF reward coupon for the referrer.`)) {
      return;
    }
    setActioningId(record.id);

    try {
      // 1. Generate unique coupon
      let uniqueRewardCode = "";
      let isUnique = false;
      let retries = 5;

      while (!isUnique && retries > 0) {
        const randStr = Math.random().toString(36).substring(2, 8).toUpperCase();
        uniqueRewardCode = `REF-${randStr}`;

        const { data: existingCoupon } = await supabase
          .from("coupons")
          .select("id")
          .eq("code", uniqueRewardCode)
          .maybeSingle();

        if (!existingCoupon) {
          isUnique = true;
        }
        retries--;
      }

      if (!isUnique) {
        uniqueRewardCode = `REF-${Date.now().toString().slice(-6)}`;
      }

      const now = new Date();
      const expiryDate = new Date();
      expiryDate.setDate(now.getDate() + 30);

      // 2. Insert coupon
      const { data: newCoupon, error: couponError } = await supabase
        .from("coupons")
        .insert({
          code: uniqueRewardCode,
          name: `Manual Referral Reward`,
          discount_type: "percentage",
          discount_value: 20.00,
          min_order_value: 0.00,
          start_date: now.toISOString(),
          expiry_date: expiryDate.toISOString(),
          max_uses: 1,
          max_uses_per_customer: 1,
          is_active: true,
          description: `20% OFF Referral Reward Coupon generated by admin.`
        })
        .select()
        .single();

      if (couponError || !newCoupon) {
        alert("Error creating reward coupon: " + (couponError?.message || "Unknown error"));
        setActioningId(null);
        return;
      }

      // 3. Assign coupon to Referrer
      const { error: assignError } = await supabase
        .from("user_coupons")
        .insert({
          user_id: record.referrer_id,
          coupon_id: newCoupon.id,
          status: "active"
        });

      if (assignError) {
        alert("Error assigning coupon: " + assignError.message);
        setActioningId(null);
        return;
      }

      // 4. Update referral log status
      const { error: recordError } = await supabase
        .from("referral_records")
        .update({
          status: "successful",
          reward_status: "rewarded"
        })
        .eq("id", record.id);

      if (recordError) {
        alert("Error updating referral record status: " + recordError.message);
      } else {
        alert(`Referral approved successfully! Coupon "${uniqueRewardCode}" assigned.`);
        fetchReferrals();
      }

    } catch (err: any) {
      console.error(err);
      alert("Unexpected error actioning approval: " + err.message);
    } finally {
      setActioningId(null);
    }
  };

  const handleReject = async (id: string) => {
    if (!window.confirm("Are you sure you want to reject this referral?")) {
      return;
    }
    setActioningId(id);
    const { error } = await supabase
      .from("referral_records")
      .update({ status: "rejected" })
      .eq("id", id);

    if (error) {
      alert("Error rejecting referral: " + error.message);
    } else {
      fetchReferrals();
    }
    setActioningId(null);
  };

  const handleExportCSV = () => {
    if (filteredReferrals.length === 0) return;

    const headers = ["Referrer Name", "Referrer Email", "Friend Name", "Friend Email", "Status", "Reward Status", "Referral Date"];
    
    const rows = filteredReferrals.map((r) => [
      r.referrer?.full_name || "N/A",
      r.referrer?.email || "N/A",
      r.referred?.full_name || "N/A",
      r.referred?.email || "N/A",
      r.status,
      r.reward_status,
      new Date(r.created_at).toLocaleString(),
    ]);

    const csvContent = [
      headers.join(","),
      ...rows.map((row) =>
        row
          .map((value) => {
            const escaped = String(value).replace(/"/g, '""');
            return `"${escaped}"`;
          })
          .join(",")
      ),
    ].join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `kyu_referrals_${new Date().toISOString().split("T")[0]}.csv`);
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Filter logs locally
  const filteredReferrals = referrals.filter(r => {
    const rName = r.referrer?.full_name?.toLowerCase() || "";
    const rEmail = r.referrer?.email?.toLowerCase() || "";
    const fName = r.referred?.full_name?.toLowerCase() || "";
    const fEmail = r.referred?.email?.toLowerCase() || "";
    const query = searchQuery.toLowerCase();

    const matchesSearch = rName.includes(query) || rEmail.includes(query) || fName.includes(query) || fEmail.includes(query);
    const matchesFilter = statusFilter === "all" || r.status === statusFilter;

    return matchesSearch && matchesFilter;
  });

  if (loading && referrals.length === 0) return <div className="text-gray-500 font-mono text-sm uppercase">Loading Database...</div>;

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-xl font-bold uppercase tracking-widest">Referral Records</h2>
          <p className="text-xs text-gray-500 mt-1 uppercase tracking-wider">
            Total Logs: {referrals.length} | Filtered: {filteredReferrals.length}
          </p>
        </div>

        <div className="flex w-full sm:w-auto gap-3 items-center">
          {/* Search bar */}
          <div className="relative w-full sm:w-64">
            <Search className="w-4 h-4 text-gray-500 absolute left-3 top-3" />
            <input
              type="text"
              placeholder="SEARCH REFERRER/FRIEND..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full bg-black border border-white/20 rounded pl-9 pr-3 py-2 text-white text-xs uppercase tracking-widest focus:border-white focus:outline-none placeholder-gray-500"
            />
          </div>

          {/* Status selector */}
          <select 
            value={statusFilter} 
            onChange={(e) => setStatusFilter(e.target.value)}
            className="bg-black border border-white/20 rounded px-3 py-2 text-white text-xs uppercase tracking-widest focus:border-white focus:outline-none"
          >
            <option value="all">All Statuses</option>
            <option value="pending">Pending</option>
            <option value="successful">Successful</option>
            <option value="rewarded">Rewarded</option>
            <option value="rejected">Rejected</option>
          </select>

          <button
            onClick={handleExportCSV}
            disabled={filteredReferrals.length === 0}
            className="flex items-center gap-2 px-4 py-2 border border-white/20 hover:border-white bg-transparent hover:bg-white/5 disabled:border-white/10 disabled:text-gray-600 disabled:bg-transparent disabled:cursor-not-allowed transition-all duration-300 rounded-lg text-xs uppercase tracking-widest font-semibold"
          >
            <Download className="w-4 h-4" /> Export
          </button>
        </div>
      </div>

      {/* Database logs table */}
      <div className="bg-[#111] border border-white/10 rounded-xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm whitespace-nowrap min-w-[900px]">
            <thead className="bg-white/5 uppercase tracking-widest text-xs text-gray-400 border-b border-white/10">
              <tr>
                <th className="px-6 py-4">Referrer</th>
                <th className="px-6 py-4">Friend (Referred User)</th>
                <th className="px-6 py-4">Referral Date</th>
                <th className="px-6 py-4">Status</th>
                <th className="px-6 py-4">Reward</th>
                <th className="px-6 py-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/10">
              {filteredReferrals.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-8 text-center text-gray-500 uppercase tracking-widest text-xs font-mono">
                    No referral records matched criteria.
                  </td>
                </tr>
              ) : (
                filteredReferrals.map((record) => {
                  const isPending = record.status === "pending";
                  return (
                    <tr key={record.id} className="hover:bg-white/5 transition-colors">
                      <td className="px-6 py-4 font-mono text-xs">
                        <div className="font-sans font-bold text-white text-sm">{record.referrer?.full_name || "N/A"}</div>
                        <div className="text-gray-400 mt-0.5">{record.referrer?.email}</div>
                      </td>
                      <td className="px-6 py-4 font-mono text-xs">
                        <div className="font-sans font-bold text-white text-sm">{record.referred?.full_name || "N/A"}</div>
                        <div className="text-gray-400 mt-0.5">{record.referred?.email}</div>
                      </td>
                      <td className="px-6 py-4 text-gray-500 font-mono text-xs">
                        {new Date(record.created_at).toLocaleString()}
                      </td>
                      <td className="px-6 py-4">
                        <span className={`px-2 py-0.5 rounded text-[10px] uppercase tracking-widest border font-semibold ${
                          record.status === "successful" || record.status === "rewarded"
                            ? "border-green-500/20 text-green-500 bg-green-500/5"
                            : record.status === "pending"
                              ? "border-yellow-500/20 text-yellow-500 bg-yellow-500/5"
                              : "border-red-500/20 text-red-500 bg-red-500/5"
                        }`}>
                          {record.status}
                        </span>
                      </td>
                      <td className="px-6 py-4 font-mono text-xs">
                        <span className={record.reward_status === "rewarded" ? "text-cyan-400" : "text-gray-500"}>
                          {record.reward_status === "rewarded" ? "20% COUPON ISSUED" : "NO REWARD"}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-right">
                        {isPending ? (
                          <div className="flex justify-end gap-2">
                            <button
                              onClick={() => handleApprove(record)}
                              disabled={actioningId === record.id}
                              className="flex items-center gap-1 bg-green-500/10 hover:bg-green-500 text-green-400 hover:text-black border border-green-500/20 px-3 py-1 rounded text-xs font-semibold transition-all uppercase tracking-widest"
                            >
                              <CheckCircle2 className="w-3.5 h-3.5" /> Approve
                            </button>
                            <button
                              onClick={() => handleReject(record.id)}
                              disabled={actioningId === record.id}
                              className="flex items-center gap-1 bg-red-500/10 hover:bg-red-500 text-red-400 hover:text-black border border-red-500/20 px-3 py-1 rounded text-xs font-semibold transition-all uppercase tracking-widest"
                            >
                              <XCircle className="w-3.5 h-3.5" /> Reject
                            </button>
                          </div>
                        ) : (
                          <span className="text-gray-500 text-[10px] uppercase tracking-widest font-mono">Completed</span>
                        )}
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
